version: 2
jobs:
    build:
        docker:
            - image: circleci/java:8-jdk
        steps:
            - checkout
            - setup_remote_docker
            - restore_cache:
                key: hello-mvn-dependencies
            - run:
                name: Maven Package
                command: mvn package
            - run:
                name: Build docker image
                command: docker build -t leward/hello .
            - run:
                name: Login to docker repository
                command: docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD
            - run:
                name: Push to docker repository
                command: docker push leward/hello
            - save_cache:
                key: sg-tryout-mvn-dependencies
                paths:
                    - ~/.m2
    rancher:
        docker:
            - image: circleci/java:8-jdk
        steps:
            - checkout
            - run:
                name: Install rancher-compose
                command: curl -sSL "https://github.com/rancher/rancher-compose/releases/download/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz" | tar -xzp --strip-components=2
            - run:
                name: Deploy to rancher
                command: ./rancher-compose --project-name hello up -d --pull --force-upgrade --confirm-upgrade
    sonar:
        docker:
            - image: circleci/java:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: hello-mvn-dependencies-sonar
            - run:
                name: SonarQube analysis
                command: |
                    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.organization=leward-github \
                        -Dsonar.login=$SONAR_LOGIN
            - save_cache:
                key: sg-tryout-mvn-dependencies-sonar
                paths:
                    - ~/.m2
    sonar_pull_request:
        docker:
            - image: circleci/java:8-jdk
        steps:
            - checkout
            - restore_cache:
                key: hello-mvn-dependencies-sonar
            - run:
                name: SonarQube analysis
                command: |
                    if [ $CIRCLE_PULL_REQUEST ]; then mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
                        -Dsonar.host.url=https://sonarcloud.io \
                        -Dsonar.organization=leward-github \
                        -Dsonar.login=$SONAR_LOGIN \
                        -Dsonar.analysis.mode=preview \
                        -Dsonar.github.pullRequest=$(echo $CIRCLE_PULL_REQUEST | awk -F'/' '{print $NF}') \
                        -Dsonar.github.repository=Leward/hello \
                        -Dsonar.github.oauth=$GITHUB_TOKEN; fi
            - save_cache:
                key: sg-tryout-mvn-dependencies-sonar
                paths:
                    - ~/.m2Hi A
workflows:
    version: 2
    build_test_deploy:
        jobs:
            - build
            - rancher:
                filters:
                    branches:
                        only: master
                requires:
                    - build
            - sonar:
                filters:
                    branches:
                        only: master
            - sonar_pull_request:
                filters:
                    branches:
                        ignore: master
